### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Thuya-hub** [codesyncapp/codesync-atom#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Pro Insider Preview
**Thrown From**: [codesync](https://github.com/codesyncapp/codesync-atom) package 3.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At C:\Users\ASUS-TUFGaming\.atom\packages\codesync\lib\events\event_handler.js:78

TypeError: Cannot read property 'split' of undefined
    at eventHandler.handleChangeEvent (/packages/codesync/lib/events/event_handler.js:78:34)
    at /packages/codesync/lib/codesync.js:110:25
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:508389)
    at later (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:104895)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
audio-syntax 1.2.0 
audio-ui 1.1.0 
barebone-atom-package-coffee 0.0.1 
busy-signal 2.0.1 
byteskript-syntax 1.0.2 
codesync 3.3.0 
emmet 2.4.3 
emmet-jsx-props 1.4.0 
hey-pane 1.2.0 
Hydrogen 2.16.3 
intentions 2.1.1 
kite 0.206.0 
language-computercraft-rebuilt 0.2.0 
linter 3.4.0 
linter-coffeelint 2.0.88 
linter-ui-default 3.4.1 
scroll-through-time 0.3.1 
teletype 0.13.4 
tree-view-clipboard 1.0.3 
zentabs 0.8.9 
```

**Comment by Basit-qc** [comment]
Thanks you for reporting the error @Thuya-hub. Fixed this in v3.3.1. 
Feel free to reopen the issue if it still exits.
