### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '$ATOM_HOME/.git/objects/23/tmp_obj_js9vIr'

### ISSUE THREAD

**Issue by queilawithaQ** [codesyncapp/codesync-atom#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [codesync](https://github.com/codesyncapp/codesync-atom) package 2.2.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/loca/.atom/.git/objects/23/tmp_obj_js9vIr'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, lstat '/Users/loca/.atom/.git/objects/23/tmp_obj_js9vIr'
    at lstatSync (fs.js:906:3)
    at Object.fs.lstatSync (electron/js2c/asar.js:235:27)
    at handleFileCreated (/packages/codesync/lib/event_handler.js:60:12)
    at /packages/codesync/lib/codesync.js:23:11
    at Function.simpleDispatch (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at s (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:413570)
    at PathWatcher.onNativeEvents (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:27018)
    at /private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:25754
    at Function.simpleDispatch (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at NSFWNativeWatcher.onEvents (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:23000)
    at watcher.c.debounceMS (/private/var/folders/lt/7j0swcl55qb9r1xjjgv_2cxw0000gn/T/AppTranslocation/53D6994B-C07E-46F8-82C4-5A20AAA33B1B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:24649)
```

### Commands

```
     -4:38.1.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -3:16.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:15.9.0 core:copy (atom-text-editor.editor.is-focused.has-selection)
  5x -3:06.5.0 core:backspace (input.hidden-input)
     -2:41.9.0 core:paste (input.input-text.native-key-bindings)
     -2:25.9.0 core:confirm (input.hidden-input)
  9x -2:23.8.0 core:backspace (input.hidden-input)
     -2:20.1.0 core:confirm (input.hidden-input)
     -1:37.8.0 encoding-selector:show (atom-text-editor.editor)
     -0:54.3.0 tree-view:copy-full-path (div.header.list-item.project-root-header)
     -0:08.8.0 core:select-all (button.github-StagingView-headerButton.icon.icon-move-down)
```

### Non-Core Packages

```
codesync 2.2.0 
```

**Comment by Basit-qc** [comment]
Thank you for reporting the issue @queilawithaQ. [v.2.3.0](https://atom.io/packages/codesync) is out with a fix. Please try that.
